name: Build and test

on: [push, pull_request]
permissions:
  contents: read
  pull-requests: write
  id-token: write
  attestations: write
   
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 21 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git
        run: |
          git --version
          git describe --always

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ matrix.java }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven on JDK ${{ matrix.java }}
        run: mvn --batch-mode --update-snapshots verify

      - name: List build artifacts (debug)
        run: ls -R target/

      - name: Attest Build Provenance
        uses: slsa-framework/slsa-github-generator@v2.1.0
        with:
          artifact_path: target/*.jar
